language: java
jdk:
  - openjdk11

addons:
      sonarcloud:
        organization: "djeckkenni"
        sonar.login: "8561606211ed5a6a6d27d33abd8a912ed9da512d"
        token:
          secure: "e8e2dcab76c093fcfbbda062345b93982efbda7c" # encrypted value of your token
script:
  - mvn clean install
  - sonar-scanner
cache:
  directories:
    - $HOME/.m2
